# -*- coding: utf-8 -*-
"""TPS_1_Configuracion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N8vo3Tctw-tbTtLtC2Ev2xjnvw03f5B5

# DATA SCIENTIST

## CONFIGURACIÓN DEL ENTORNO

### CARGA DE LIBRERIAS
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline

"""### CARGA DE LOS DATOS"""

df = pd.read_csv('AbandonoEmpleados.csv', sep = ';', index_col= 'id', na_values='#N/D')

df